//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_service.Areas.administrateur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int idC { get; set; }
        public int @ref { get; set; }
        public int id { get; set; }
        public System.DateTime dateCommande { get; set; }
    }
}
