//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Customer_service.Areas.administrateur.Models
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class dotnetEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet dotnetEntities à l'aide de la chaîne de connexion trouvée dans la section 'dotnetEntities' du fichier de configuration d'application.
        /// </summary>
        public dotnetEntities() : base("name=dotnetEntities", "dotnetEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet dotnetEntities.
        /// </summary>
        public dotnetEntities(string connectionString) : base(connectionString, "dotnetEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet dotnetEntities.
        /// </summary>
        public dotnetEntities(EntityConnection connection) : base(connection, "dotnetEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Client> Client
        {
            get
            {
                if ((_Client == null))
                {
                    _Client = base.CreateObjectSet<Client>("Client");
                }
                return _Client;
            }
        }
        private ObjectSet<Client> _Client;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Commande> Commande
        {
            get
            {
                if ((_Commande == null))
                {
                    _Commande = base.CreateObjectSet<Commande>("Commande");
                }
                return _Commande;
            }
        }
        private ObjectSet<Commande> _Commande;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Produit> Produit
        {
            get
            {
                if ((_Produit == null))
                {
                    _Produit = base.CreateObjectSet<Produit>("Produit");
                }
                return _Produit;
            }
        }
        private ObjectSet<Produit> _Produit;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Client. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToClient(Client client)
        {
            base.AddObject("Client", client);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Commande. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCommande(Commande commande)
        {
            base.AddObject("Commande", commande);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Produit. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToProduit(Produit produit)
        {
            base.AddObject("Produit", produit);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dotnetModel", Name="Client")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Client : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Client.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="nom">Valeur initiale de la propriété nom.</param>
        /// <param name="prenom">Valeur initiale de la propriété prenom.</param>
        /// <param name="email">Valeur initiale de la propriété email.</param>
        /// <param name="adresse">Valeur initiale de la propriété adresse.</param>
        /// <param name="tel">Valeur initiale de la propriété tel.</param>
        /// <param name="username">Valeur initiale de la propriété username.</param>
        /// <param name="password">Valeur initiale de la propriété password.</param>
        public static Client CreateClient(global::System.Int32 id, global::System.String nom, global::System.String prenom, global::System.String email, global::System.String adresse, global::System.String tel, global::System.String username, global::System.String password)
        {
            Client client = new Client();
            client.id = id;
            client.nom = nom;
            client.prenom = prenom;
            client.email = email;
            client.adresse = adresse;
            client.tel = tel;
            client.username = username;
            client.password = password;
            return client;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false, "nom");
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                OnprenomChanging(value);
                ReportPropertyChanging("prenom");
                _prenom = StructuralObject.SetValidValue(value, false, "prenom");
                ReportPropertyChanged("prenom");
                OnprenomChanged();
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adresse
        {
            get
            {
                return _adresse;
            }
            set
            {
                OnadresseChanging(value);
                ReportPropertyChanging("adresse");
                _adresse = StructuralObject.SetValidValue(value, false, "adresse");
                ReportPropertyChanged("adresse");
                OnadresseChanged();
            }
        }
        private global::System.String _adresse;
        partial void OnadresseChanging(global::System.String value);
        partial void OnadresseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tel
        {
            get
            {
                return _tel;
            }
            set
            {
                OntelChanging(value);
                ReportPropertyChanging("tel");
                _tel = StructuralObject.SetValidValue(value, false, "tel");
                ReportPropertyChanged("tel");
                OntelChanged();
            }
        }
        private global::System.String _tel;
        partial void OntelChanging(global::System.String value);
        partial void OntelChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dotnetModel", Name="Commande")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Commande : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Commande.
        /// </summary>
        /// <param name="idC">Valeur initiale de la propriété idC.</param>
        /// <param name="ref">Valeur initiale de la propriété ref.</param>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="dateCommande">Valeur initiale de la propriété dateCommande.</param>
        public static Commande CreateCommande(global::System.Int32 idC, global::System.Int32 @ref, global::System.Int32 id, global::System.DateTime dateCommande)
        {
            Commande commande = new Commande();
            commande.idC = idC;
            commande.@ref = @ref;
            commande.id = id;
            commande.dateCommande = dateCommande;
            return commande;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idC
        {
            get
            {
                return _idC;
            }
            set
            {
                if (_idC != value)
                {
                    OnidCChanging(value);
                    ReportPropertyChanging("idC");
                    _idC = StructuralObject.SetValidValue(value, "idC");
                    ReportPropertyChanged("idC");
                    OnidCChanged();
                }
            }
        }
        private global::System.Int32 _idC;
        partial void OnidCChanging(global::System.Int32 value);
        partial void OnidCChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 @ref
        {
            get
            {
                return _ref;
            }
            set
            {
                OnrefChanging(value);
                ReportPropertyChanging("ref");
                _ref = StructuralObject.SetValidValue(value, "ref");
                ReportPropertyChanged("ref");
                OnrefChanged();
            }
        }
        private global::System.Int32 _ref;
        partial void OnrefChanging(global::System.Int32 value);
        partial void OnrefChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value, "id");
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateCommande
        {
            get
            {
                return _dateCommande;
            }
            set
            {
                OndateCommandeChanging(value);
                ReportPropertyChanging("dateCommande");
                _dateCommande = StructuralObject.SetValidValue(value, "dateCommande");
                ReportPropertyChanged("dateCommande");
                OndateCommandeChanged();
            }
        }
        private global::System.DateTime _dateCommande;
        partial void OndateCommandeChanging(global::System.DateTime value);
        partial void OndateCommandeChanged();

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dotnetModel", Name="Produit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produit : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Produit.
        /// </summary>
        /// <param name="ref">Valeur initiale de la propriété ref.</param>
        /// <param name="designation">Valeur initiale de la propriété designation.</param>
        /// <param name="prix">Valeur initiale de la propriété prix.</param>
        /// <param name="couleur">Valeur initiale de la propriété couleur.</param>
        /// <param name="photo">Valeur initiale de la propriété photo.</param>
        public static Produit CreateProduit(global::System.Int32 @ref, global::System.String designation, global::System.Single prix, global::System.String couleur, global::System.Byte[] photo)
        {
            Produit produit = new Produit();
            produit.@ref = @ref;
            produit.designation = designation;
            produit.prix = prix;
            produit.couleur = couleur;
            produit.photo = photo;
            return produit;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 @ref
        {
            get
            {
                return _ref;
            }
            set
            {
                if (_ref != value)
                {
                    OnrefChanging(value);
                    ReportPropertyChanging("ref");
                    _ref = StructuralObject.SetValidValue(value, "ref");
                    ReportPropertyChanged("ref");
                    OnrefChanged();
                }
            }
        }
        private global::System.Int32 _ref;
        partial void OnrefChanging(global::System.Int32 value);
        partial void OnrefChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String designation
        {
            get
            {
                return _designation;
            }
            set
            {
                OndesignationChanging(value);
                ReportPropertyChanging("designation");
                _designation = StructuralObject.SetValidValue(value, false, "designation");
                ReportPropertyChanged("designation");
                OndesignationChanged();
            }
        }
        private global::System.String _designation;
        partial void OndesignationChanging(global::System.String value);
        partial void OndesignationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single prix
        {
            get
            {
                return _prix;
            }
            set
            {
                OnprixChanging(value);
                ReportPropertyChanging("prix");
                _prix = StructuralObject.SetValidValue(value, "prix");
                ReportPropertyChanged("prix");
                OnprixChanged();
            }
        }
        private global::System.Single _prix;
        partial void OnprixChanging(global::System.Single value);
        partial void OnprixChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String couleur
        {
            get
            {
                return _couleur;
            }
            set
            {
                OncouleurChanging(value);
                ReportPropertyChanging("couleur");
                _couleur = StructuralObject.SetValidValue(value, false, "couleur");
                ReportPropertyChanged("couleur");
                OncouleurChanged();
            }
        }
        private global::System.String _couleur;
        partial void OncouleurChanging(global::System.String value);
        partial void OncouleurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] photo
        {
            get
            {
                return StructuralObject.GetValidValue(_photo);
            }
            set
            {
                OnphotoChanging(value);
                ReportPropertyChanging("photo");
                _photo = StructuralObject.SetValidValue(value, false, "photo");
                ReportPropertyChanged("photo");
                OnphotoChanged();
            }
        }
        private global::System.Byte[] _photo;
        partial void OnphotoChanging(global::System.Byte[] value);
        partial void OnphotoChanged();

        #endregion

    }

    #endregion

}
